export const countryCodes = [
  { code: '1', country: 'United States 🇺🇸' },
  { code: '44', country: 'United Kingdom 🇬🇧' },
  { code: '234', country: 'Nigeria 🇳🇬' },
  { code: '91', country: 'India 🇮🇳' },
  { code: '81', country: 'Japan 🇯🇵' },
  { code: '49', country: 'Germany 🇩🇪' },
  { code: '33', country: 'France 🇫🇷' },
  { code: '86', country: 'China 🇨🇳' },
  { code: '55', country: 'Brazil 🇧🇷' },
  { code: '27', country: 'South Africa 🇿🇦' },
  { code: '92', country: 'Pakistan 🇵🇰' },
  { code: '972', country: 'Israel 🇮🇱' },
  { code: '39', country: 'Italy 🇮🇹' },
  { code: '7', country: 'Russia 🇷🇺' },
  { code: '61', country: 'Australia 🇦🇺' },
  { code: '82', country: 'South Korea 🇰🇷' },
  { code: '34', country: 'Spain 🇪🇸' },
  { code: '62', country: 'Indonesia 🇮🇩' },
  { code: '351', country: 'Portugal 🇵🇹' },
  { code: '90', country: 'Turkey 🇹🇷' },
  { code: '966', country: 'Saudi Arabia 🇸🇦' },
  { code: '20', country: 'Egypt 🇪🇬' },
  { code: '886', country: 'Taiwan 🇹🇼' },
  { code: '31', country: 'Netherlands 🇳🇱' },
  { code: '47', country: 'Norway 🇳🇴' },
  { code: '46', country: 'Sweden 🇸🇪' },
  { code: '32', country: 'Belgium 🇧🇪' },
  { code: '45', country: 'Denmark 🇩🇰' },
  { code: '48', country: 'Poland 🇵🇱' },
  { code: '52', country: 'Mexico 🇲🇽' },
  { code: '420', country: 'Czech Republic 🇨🇿' },
  { code: '358', country: 'Finland 🇫🇮' },
  { code: '84', country: 'Vietnam 🇻🇳' },
  { code: '64', country: 'New Zealand 🇳🇿' },
  { code: '380', country: 'Ukraine 🇺🇦' },
  { code: '63', country: 'Philippines 🇵🇭' },
  { code: '56', country: 'Chile 🇨🇱' },
  { code: '60', country: 'Malaysia 🇲🇾' },
  { code: '357', country: 'Cyprus 🇨🇾' },
  { code: '41', country: 'Switzerland 🇨🇭' },
  { code: '36', country: 'Hungary 🇭🇺' },
  { code: '965', country: 'Kuwait 🇰🇼' },
  { code: '973', country: 'Bahrain 🇧🇭' },
  { code: '974', country: 'Qatar 🇶🇦' },
  { code: '372', country: 'Estonia 🇪🇪' },
  { code: '40', country: 'Romania 🇷🇴' },
  { code: '375', country: 'Belarus 🇧🇾' },
  { code: '359', country: 'Bulgaria 🇧🇬' },
  { code: '98', country: 'Iran 🇮🇷' },
  { code: '964', country: 'Iraq 🇮🇶' },
  { code: '992', country: 'Tajikistan 🇹🇯' },
  { code: '993', country: 'Turkmenistan 🇹🇲' },
  { code: '994', country: 'Azerbaijan 🇦🇿' },
  { code: '995', country: 'Georgia 🇬🇪' },
  { code: '996', country: 'Kyrgyzstan 🇰🇬' },
  { code: '998', country: 'Uzbekistan 🇺🇿' },
  { code: '501', country: 'Belize 🇧🇿' },
  { code: '502', country: 'Guatemala 🇬🇹' },
  { code: '503', country: 'El Salvador 🇸🇻' },
  { code: '504', country: 'Honduras 🇭🇳' },
  { code: '505', country: 'Nicaragua 🇳🇮' },
  { code: '506', country: 'Costa Rica 🇨🇷' },
  { code: '507', country: 'Panama 🇵🇦' },
  { code: '509', country: 'Haiti 🇭🇹' },
  { code: '592', country: 'Guyana 🇬🇾' },
  { code: '595', country: 'Paraguay 🇵🇾' },
  { code: '597', country: 'Suriname 🇸🇷' },
  { code: '598', country: 'Uruguay 🇺🇾' },
  { code: '680', country: 'Palau 🇵🇼' },
  { code: '679', country: 'Fiji 🇫🇯' },
  { code: '678', country: 'Vanuatu 🇻🇺' },
  { code: '677', country: 'Solomon Islands 🇸🇧' },
  { code: '676', country: 'Tonga 🇹🇴' },
  { code: '675', country: 'Papua New Guinea 🇵🇬' },
  { code: '674', country: 'Nauru 🇳🇷' },
  { code: '673', country: 'Brunei 🇧🇳' },
  { code: '672', country: 'Antarctica 🇦🇶' },
  { code: '971', country: 'United Arab Emirates 🇦🇪' },
  { code: '966', country: 'Saudi Arabia 🇸🇦' },
  { code: '965', country: 'Kuwait 🇰🇼' },
  { code: '968', country: 'Oman 🇴🇲' },
  { code: '967', country: 'Yemen 🇾🇪' },
];
